# Generated by Django 5.1.1 on 2024-09-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.level'),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.subcategory'),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.category'),
        ),
    ]
