# Generated by Django 5.1.1 on 2024-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='destination',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
