# Generated by Django 5.1.1 on 2024-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='submitted_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='submitted_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
