# Generated by Django 5.1.1 on 2024-10-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_business_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.destination'),
        ),
    ]
