# Generated by Django 5.1.1 on 2024-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='project_title',
            field=models.CharField(max_length=300),
        ),
    ]
