# Generated by Django 5.1.1 on 2024-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_scrapingtask_level_scrapingtask_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
