# Generated by Django 5.1.1 on 2024-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_business_submitted_city_business_submitted_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='business',
            name='submitted_city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='submitted_country',
        ),
        migrations.AddField(
            model_name='business',
            name='form_country_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='form_country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='form_destination_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='form_destination_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
