# Generated by Django 5.1.1 on 2024-10-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_business_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.country'),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.destination'),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='destination_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
