# Generated by Django 5.1.1 on 2024-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_remove_business_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
