# Generated by Django 5.1.1 on 2024-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_business_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='main_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
