# Generated by Django 5.1.1 on 2024-09-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_businessimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='average_rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
