# Generated by Django 5.1.1 on 2024-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_event_alter_scrapingtask_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('TRANSLATED', 'TRANSLATED'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
    ]
