# Generated by Django 5.1.1 on 2024-09-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_rename_average_rating_business_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('DISCARDED', 'Discarded'), ('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('IN_PRODUCTION', 'In Production')], default='PENDING', max_length=20),
        ),
    ]
