# Generated by Django 5.1.1 on 2024-10-09 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_image_is_approved_alter_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
