# Generated by Django 5.1.1 on 2024-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_alter_scrapingtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='translation_status',
            field=models.CharField(choices=[('PENDING_TRANSLATION', 'Pending Translation'), ('IN_PROGRESS', 'In Progress'), ('TRANSLATED', 'Translated'), ('TRANSLATION_FAILED', 'Translation Failed')], default='PENDING_TRANSLATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scraping_files/'),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
    ]
