# Generated by Django 5.1.1 on 2024-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_scrapingtask_translation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='main_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='tailored_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
