# Generated by Django 5.1.1 on 2024-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_scrapingtask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='report_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
