# Generated by Django 5.1.1 on 2024-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_alter_business_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
