# Generated by Django 5.1.1 on 2024-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_image_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='site_types',
            field=models.CharField(choices=[('PLACE', 'Place'), ('EVENT', 'Event')], default='PLACE', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='translated_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='translated_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='translated_main_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='translated_tailored_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='translated_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='translation_status',
            field=models.CharField(choices=[('PENDING_TRANSLATION', 'Pending Translation'), ('IN_PROGRESS', 'In Progress'), ('TRANSLATED', 'Translated'), ('PARTIALLY_TRANSLATED', 'Partially Translated'), ('TRANSLATION_FAILED', 'Translation Failed')], default='PENDING_TRANSLATION', max_length=20),
        ),
    ]
