# Generated by Django 5.1.1 on 2024-12-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_business_site_types_business_translated_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Feedback Content')),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='INITIAL', max_length=20, verbose_name='Feedback Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='automation.business')),
            ],
        ),
    ]
