# Generated by Django 5.1.1 on 2024-12-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_remove_business_destination_alter_image_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AddField(
            model_name='level',
            name='site_types',
            field=models.CharField(choices=[('PLACE', 'Place'), ('EVENT', 'Event')], default='PLACE', max_length=20),
        ),
    ]
