# Generated by Django 5.1.1 on 2024-12-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_alter_level_options_remove_business_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='destination',
        ),
        migrations.AddField(
            model_name='category',
            name='ls_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='ls_id',
            field=models.IntegerField(default=0),
        ),
    ]
