# Generated by Django 5.1.1 on 2024-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_remove_business_destination_category_ls_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ls_id',
            field=models.IntegerField(db_comment="Reference of Local secret's Country model.", default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='ls_id',
            field=models.IntegerField(db_comment="Reference of Local secret's City model.", default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='ls_id',
            field=models.IntegerField(db_comment="Reference of Local secret's Category / Sub category model.", default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='ls_id',
            field=models.IntegerField(db_comment="Reference of Local secret's Level model.", default=0),
        ),
    ]
