# Generated by Django 5.1.1 on 2024-12-16 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_country_ls_id_destination_ls_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('live_busyness_info', models.CharField(blank=True, max_length=50, null=True)),
                ('time_spent', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_times', to='automation.business')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyBusyness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('6 AM', '6 AM'), ('7 AM', '7 AM'), ('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM'), ('6 PM', '6 PM'), ('7 PM', '7 PM'), ('8 PM', '8 PM'), ('9 PM', '9 PM'), ('10 PM', '10 PM'), ('11 PM', '11 PM')], max_length=5)),
                ('busyness_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('popular_times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_data', to='automation.populartimes')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddIndex(
            model_name='populartimes',
            index=models.Index(fields=['business', 'day'], name='automation__busines_015b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='populartimes',
            unique_together={('business', 'day')},
        ),
        migrations.AddIndex(
            model_name='hourlybusyness',
            index=models.Index(fields=['popular_times', 'time'], name='automation__popular_46c96f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlybusyness',
            unique_together={('popular_times', 'time')},
        ),
    ]
