# Generated by Django 5.1.1 on 2024-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_populartimes_hourlybusyness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='title_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='title_esp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='title_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='translated_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AMBASSADOR', 'Ambassador')], max_length=20),
        ),
    ]
