# Generated by Django 5.1.1 on 2024-12-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_alter_business_title_eng_alter_business_title_esp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapingtask',
            options={'verbose_name': 'Sites Gathering', 'verbose_name_plural': 'Sites Gatherings'},
        ),
        migrations.AddField(
            model_name='business',
            name='types_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='types_esp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='types_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='scraped_at',
            field=models.DateTimeField(verbose_name='gathered_at'),
        ),
        migrations.CreateModel(
            name='TranslationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'timestamp'], name='automation__busines_d508a0_idx')],
            },
        ),
    ]
