# Generated by Django 5.1.1 on 2025-01-21 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_alter_scrapingtask_options_business_types_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_image_count', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'READY TO REVIEW'), ('FAILED', 'FAILED'), ('DONE', 'REVIEWED'), ('TASK_DONE', 'LIVE')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'parent')},
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='automation__status_d22962_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['title'], name='automation__title_036f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['scraped_at'], name='automation__scraped_7ff5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['form_destination_id'], name='automation__form_de_37a1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['main_category'], name='automation__main_ca_137bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city'], name='automation__city_729e75_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='automation__title_13caeb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'title'], name='automation__parent__e292db_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['business'], name='automation__busines_6c6670_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='automation__status_b85aac_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingtask',
            index=models.Index(fields=['status'], name='automation__status_cafa72_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingtask',
            index=models.Index(fields=['created_at'], name='automation__created_211118_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingtask',
            index=models.Index(fields=['destination'], name='automation__destina_ef33b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='automation__role_1378d3_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='automation__user_id_5e0a0a_idx'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.country'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.destination'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.level'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_main_category_prefs', to='automation.category'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_subcategory_prefs', to='automation.category'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
