# Generated by Django 5.1.1 on 2025-02-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_userpreference_alter_scrapingtask_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={},
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='last_main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category_prefs', to='automation.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='last_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_prefs', to='automation.category'),
        ),
        migrations.CreateModel(
            name='TagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_tag', models.CharField(max_length=120, unique=True)),
                ('uk_tag', models.CharField(max_length=120, null=True)),
                ('spanish_tag', models.CharField(max_length=120, null=True)),
                ('french_tag', models.CharField(max_length=120, null=True)),
                ('tag_ls_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['english_tag'], name='automation__english_57a3a6_idx'), models.Index(fields=['uk_tag'], name='automation__uk_tag_c22866_idx'), models.Index(fields=['spanish_tag'], name='automation__spanish_31331f_idx'), models.Index(fields=['french_tag'], name='automation__french__6d0848_idx'), models.Index(fields=['tag_ls_id'], name='automation__tag_ls__b0306e_idx')],
            },
        ),
    ]
